ALTER TABLE "T_BASE_COMPANY"
ADD ( "BANK_NAME" VARCHAR2(255) DEFAULT ''  NULL  ) 
ADD ( "BANK_ADDRESS" VARCHAR2(255) DEFAULT ''  NULL  ) 
ADD ( "BANK_ACCOUNT" VARCHAR2(255) DEFAULT ''  NULL  ) ;

COMMENT ON COLUMN "T_BASE_COMPANY"."BANK_NAME" IS '开户银行';

COMMENT ON COLUMN "T_BASE_COMPANY"."BANK_ADDRESS" IS '开户银行地址';

COMMENT ON COLUMN "T_BASE_COMPANY"."BANK_ACCOUNT" IS '供应商银行账号';

